/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer;

import Manager.Add_Food;
import User.Home;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
   
public class Review extends javax.swing.JFrame {
 Connection con = null;
	PreparedStatement pst = null;
    /**
     * Creates new form Review
     */
    public Review() {
        initComponents();
        showpic();
    }

    
      public void showpic()
    {
        ImageIcon icon = new ImageIcon("E:\\Enginnering Folder\\java\\Restaurent Managment Project\\src\\Picture\\303587.jpg");
        jLabel10.setIcon(icon);
        //scaling image for fit
        Image img = icon.getImage();
        Image imageScale = img.getScaledInstance(jLabel10.getWidth(), jLabel10.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imageScale);
        jLabel10.setIcon(scaledIcon);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnMenuCustomer = new javax.swing.JButton();
        btnBestSellersCustomer = new javax.swing.JButton();
        btnMakeOrderCustomer = new javax.swing.JButton();
        btnOrdersCustomer = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        account = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rank = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        comment = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnMenuCustomer1 = new javax.swing.JButton();
        btnBestSellersCustomer1 = new javax.swing.JButton();
        btnOrdersCustomer1 = new javax.swing.JButton();
        btnLogout1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 120, 1096, 624));
        setMaximumSize(new java.awt.Dimension(1096, 624));
        setMinimumSize(new java.awt.Dimension(1096, 624));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1096, 624));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Edwardian Script ITC", 1, 26)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 51));
        jLabel9.setText("KHS Cafe & Restaurent");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 10, 290, 70);

        btnMenuCustomer.setBackground(new java.awt.Color(13, 14, 14));
        btnMenuCustomer.setForeground(new java.awt.Color(0, 16, 14));
        btnMenuCustomer.setText("Menu");
        btnMenuCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuCustomerActionPerformed(evt);
            }
        });
        jPanel3.add(btnMenuCustomer);
        btnMenuCustomer.setBounds(320, 20, 100, 58);

        btnBestSellersCustomer.setBackground(new java.awt.Color(13, 14, 14));
        btnBestSellersCustomer.setForeground(new java.awt.Color(0, 16, 14));
        btnBestSellersCustomer.setText("Best Selling Food");
        btnBestSellersCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBestSellersCustomerActionPerformed(evt);
            }
        });
        jPanel3.add(btnBestSellersCustomer);
        btnBestSellersCustomer.setBounds(430, 20, 194, 60);

        btnMakeOrderCustomer.setBackground(new java.awt.Color(13, 14, 14));
        btnMakeOrderCustomer.setForeground(new java.awt.Color(0, 16, 14));
        btnMakeOrderCustomer.setText("Order");
        btnMakeOrderCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeOrderCustomerActionPerformed(evt);
            }
        });
        jPanel3.add(btnMakeOrderCustomer);
        btnMakeOrderCustomer.setBounds(650, 20, 120, 60);

        btnOrdersCustomer.setBackground(new java.awt.Color(13, 14, 14));
        btnOrdersCustomer.setForeground(new java.awt.Color(0, 16, 14));
        btnOrdersCustomer.setText("Your Orders");
        btnOrdersCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersCustomerActionPerformed(evt);
            }
        });
        jPanel3.add(btnOrdersCustomer);
        btnOrdersCustomer.setBounds(790, 20, 170, 60);

        btnLogout.setBackground(new java.awt.Color(13, 14, 14));
        btnLogout.setForeground(new java.awt.Color(0, 16, 14));
        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel3.add(btnLogout);
        btnLogout.setBounds(980, 20, 100, 60);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(-5, 5, 1100, 90);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1100, 0);

        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Edwardian Script ITC", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Put Your Review Here  ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(300, 10, 430, 80);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(270, 100, 140, 30);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel2.add(name);
        name.setBounds(430, 100, 270, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Account :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(270, 140, 140, 30);
        jPanel2.add(account);
        account.setBounds(430, 140, 270, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("E-Mail :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(270, 180, 140, 30);
        jPanel2.add(email);
        email.setBounds(430, 180, 270, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mobile Number : ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(270, 220, 140, 30);
        jPanel2.add(number);
        number.setBounds(430, 220, 270, 30);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Food ID : ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(270, 260, 140, 30);
        jPanel2.add(id);
        id.setBounds(430, 260, 270, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Give Rank :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(270, 300, 140, 30);
        jPanel2.add(rank);
        rank.setBounds(430, 300, 270, 30);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Comment :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(270, 360, 140, 30);

        comment.setColumns(20);
        comment.setRows(5);
        jScrollPane1.setViewportView(comment);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(430, 340, 270, 86);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(490, 450, 150, 40);

        jLabel10.setText("jLabel10");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(0, 0, 1100, 530);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 100, 1100, 530);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(null);

        btnMenuCustomer1.setBackground(new java.awt.Color(150, 105, 50));
        btnMenuCustomer1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnMenuCustomer1.setForeground(new java.awt.Color(150, 105, 50));
        btnMenuCustomer1.setText("Create Your Order");
        btnMenuCustomer1.setBorderPainted(false);
        btnMenuCustomer1.setContentAreaFilled(false);
        btnMenuCustomer1.setFocusPainted(false);
        btnMenuCustomer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuCustomer1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnMenuCustomer1);
        btnMenuCustomer1.setBounds(750, 20, 170, 58);

        btnBestSellersCustomer1.setBackground(new java.awt.Color(150, 105, 50));
        btnBestSellersCustomer1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnBestSellersCustomer1.setForeground(new java.awt.Color(150, 105, 50));
        btnBestSellersCustomer1.setText("Your Bank Account");
        btnBestSellersCustomer1.setBorderPainted(false);
        btnBestSellersCustomer1.setContentAreaFilled(false);
        btnBestSellersCustomer1.setFocusPainted(false);
        btnBestSellersCustomer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBestSellersCustomer1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnBestSellersCustomer1);
        btnBestSellersCustomer1.setBounds(580, 20, 180, 60);

        btnOrdersCustomer1.setBackground(new java.awt.Color(150, 105, 50));
        btnOrdersCustomer1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnOrdersCustomer1.setForeground(new java.awt.Color(150, 105, 50));
        btnOrdersCustomer1.setText("Menu");
        btnOrdersCustomer1.setBorderPainted(false);
        btnOrdersCustomer1.setContentAreaFilled(false);
        btnOrdersCustomer1.setFocusPainted(false);
        btnOrdersCustomer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersCustomer1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnOrdersCustomer1);
        btnOrdersCustomer1.setBounds(910, 20, 86, 60);

        btnLogout1.setBackground(new java.awt.Color(150, 105, 50));
        btnLogout1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnLogout1.setForeground(new java.awt.Color(150, 105, 50));
        btnLogout1.setText("Log Out");
        btnLogout1.setBorderPainted(false);
        btnLogout1.setContentAreaFilled(false);
        btnLogout1.setFocusPainted(false);
        btnLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnLogout1);
        btnLogout1.setBounds(990, 20, 100, 60);

        jButton2.setFont(new java.awt.Font("Edwardian Script ITC", 1, 30)); // NOI18N
        jButton2.setForeground(new java.awt.Color(187, 118, 32));
        jButton2.setText("KHS Cafe & Restaurent  ");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);
        jButton2.setBounds(0, 0, 340, 90);

        jButton3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(150, 105, 50));
        jButton3.setText("Add Bank Account");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);
        jButton3.setBounds(390, 20, 200, 60);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 1100, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuCustomerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnMenuCustomerActionPerformed

    private void btnBestSellersCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBestSellersCustomerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnBestSellersCustomerActionPerformed

    private void btnMakeOrderCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeOrderCustomerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnMakeOrderCustomerActionPerformed

    private void btnOrdersCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersCustomerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnOrdersCustomerActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          if(name.getText().equals("")||account.getText().equals("")||email.getText().equals("")||number.getText().equals("")||id.getText().equals("")||rank.getText().equals(""))
         {
             JOptionPane.showMessageDialog(null, "Enter All information");
            
         }
         
                                               else
            {
                                        
					try
					{
						Class.forName("com.mysql.jdbc.Driver");
						String query = "INSERT INTO `review`(`Name`, `Account`, `Email`, `Mobile_Number`, `Food_ID`, `Rank`, `Comment`) VALUES (?,?,?,?,?,?,?)";
						con = DriverManager.getConnection("jdbc:mysql://localhost:3306/multiuserlogin", "root", "");
						pst = con.prepareStatement(query);
						pst.setString(1, name.getText());
                                                pst.setString(2, account.getText());
						pst.setString(3, email.getText());
						pst.setString(4, number.getText());
						pst.setString(5, id.getText());
						pst.setString(6, rank.getText());
						pst.setString(7, comment.getText());
                                                
						
						if(pst.executeUpdate()>0)
						{
							JOptionPane.showMessageDialog(null,"Review Done successfully");
						}
                                        
						
					} catch (Exception ex) {
                                     JOptionPane.showMessageDialog(null,"Please check all information");

                                    }
                                         try
            {
                //Add new added item into database in menu_item table
                 Class.forName("com.mysql.jdbc.Driver");
                String query = "UPDATE `menu_item` SET `Rank`=? WHERE `ID`=?";
                
						Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/multiuserlogin", "root", "");
						PreparedStatement preparedStmt = con.prepareStatement(query);
            
           
              
                //Set random itemID
               
                preparedStmt.setString(1, rank.getText());
                preparedStmt.setString(2, id.getText());
             
                preparedStmt.executeUpdate();
                
            } catch (ClassNotFoundException ex) {
          Logger.getLogger(Add_Food.class.getName()).log(Level.SEVERE, null, ex);
      } catch (SQLException ex) {
          Logger.getLogger(Add_Food.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnMenuCustomer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuCustomer1ActionPerformed
        // TODO add your handling code here:
        Order_Form o = new Order_Form();
        o.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMenuCustomer1ActionPerformed

    private void btnBestSellersCustomer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBestSellersCustomer1ActionPerformed
        // TODO add your handling code here:

        Your_bank_account b = new Your_bank_account();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBestSellersCustomer1ActionPerformed

    private void btnLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout1ActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogout1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        bank_account b = new bank_account();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnOrdersCustomer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersCustomer1ActionPerformed
        // TODO add your handling code here:
        Customer_Menu m = new Customer_Menu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnOrdersCustomer1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      Welcome m = new Welcome();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Review().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account;
    private javax.swing.JButton btnBestSellersCustomer;
    private javax.swing.JButton btnBestSellersCustomer1;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogout1;
    private javax.swing.JButton btnMakeOrderCustomer;
    private javax.swing.JButton btnMenuCustomer;
    private javax.swing.JButton btnMenuCustomer1;
    private javax.swing.JButton btnOrdersCustomer;
    private javax.swing.JButton btnOrdersCustomer1;
    private javax.swing.JTextArea comment;
    private javax.swing.JTextField email;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField number;
    private javax.swing.JTextField rank;
    // End of variables declaration//GEN-END:variables
}
