/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Manager;


import User.Home;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class manager_Your_bank_account extends javax.swing.JFrame {

    /**
     * Creates new form bank_account
     */
    Connection con = null;
	PreparedStatement pst = null;
          ResultSet rs ;
    
    public void showpic1()
    {
        ImageIcon icon = new ImageIcon("E:\\Enginnering Folder\\java\\Restaurent Managment Project\\src\\Picture\\wallpaper2you_512374.jpg");
        jLabel10.setIcon(icon);
        //scaling image for fit
        Image img = icon.getImage();
        Image imageScale = img.getScaledInstance(jLabel10.getWidth(), jLabel10.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imageScale);
        jLabel10.setIcon(scaledIcon);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnOrdersCustomer = new javax.swing.JButton();
        btnMakeOrderCustomer = new javax.swing.JButton();
        btnBestSellersCustomer = new javax.swing.JButton();
        btnMenuCustomer = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        account = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 120, 1096, 624));
        setMinimumSize(new java.awt.Dimension(1096, 624));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(null);

        btnLogout.setBackground(new java.awt.Color(13, 14, 14));
        btnLogout.setForeground(new java.awt.Color(0, 16, 14));
        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout);
        btnLogout.setBounds(980, 20, 100, 60);

        btnOrdersCustomer.setBackground(new java.awt.Color(13, 14, 14));
        btnOrdersCustomer.setForeground(new java.awt.Color(0, 16, 14));
        btnOrdersCustomer.setText("Your Orders");
        btnOrdersCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrdersCustomer);
        btnOrdersCustomer.setBounds(790, 20, 170, 60);

        btnMakeOrderCustomer.setBackground(new java.awt.Color(13, 14, 14));
        btnMakeOrderCustomer.setForeground(new java.awt.Color(0, 16, 14));
        btnMakeOrderCustomer.setText("Order");
        btnMakeOrderCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeOrderCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(btnMakeOrderCustomer);
        btnMakeOrderCustomer.setBounds(650, 20, 120, 60);

        btnBestSellersCustomer.setBackground(new java.awt.Color(13, 14, 14));
        btnBestSellersCustomer.setForeground(new java.awt.Color(0, 16, 14));
        btnBestSellersCustomer.setText("Best Selling Food");
        btnBestSellersCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBestSellersCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(btnBestSellersCustomer);
        btnBestSellersCustomer.setBounds(430, 20, 194, 60);

        btnMenuCustomer.setBackground(new java.awt.Color(13, 14, 14));
        btnMenuCustomer.setForeground(new java.awt.Color(0, 16, 14));
        btnMenuCustomer.setText("Menu");
        btnMenuCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenuCustomer);
        btnMenuCustomer.setBounds(320, 20, 100, 58);

        jLabel9.setFont(new java.awt.Font("Edwardian Script ITC", 1, 26)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 51));
        jLabel9.setText("KHS Cafe & Restaurent");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 10, 290, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 0);

        jPanel2.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Account No. : ");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(340, 240, 140, 30);

        account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountActionPerformed(evt);
            }
        });
        account.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                accountKeyPressed(evt);
            }
        });
        jPanel2.add(account);
        account.setBounds(510, 240, 240, 30);

        jLabel1.setFont(new java.awt.Font("Edwardian Script ITC", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Show Your Bank Account Information");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(180, 20, 820, 100);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(340, 280, 121, 30);
        jPanel2.add(name);
        name.setBounds(510, 280, 240, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("E-Mail :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(340, 320, 121, 40);
        jPanel2.add(email);
        email.setBounds(510, 320, 244, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mobile number :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(340, 360, 140, 30);
        jPanel2.add(number);
        number.setBounds(510, 360, 244, 30);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Refund Money :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(340, 410, 150, 26);
        jPanel2.add(date);
        date.setBounds(510, 410, 244, 30);

        jButton1.setText("<<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 582, 60, 30);

        jLabel10.setText("jLabel10");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(0, 0, 1100, 630);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1100, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnOrdersCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersCustomerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnOrdersCustomerActionPerformed

    private void btnMakeOrderCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeOrderCustomerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnMakeOrderCustomerActionPerformed

    private void btnBestSellersCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBestSellersCustomerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnBestSellersCustomerActionPerformed

    private void btnMenuCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuCustomerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnMenuCustomerActionPerformed

    private void accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountActionPerformed

    private void accountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accountKeyPressed
        // TODO add your handling code here:
          if (evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            String account1 = account.getText();
            try {
                Class.forName("com.mysql.jdbc.Driver");
                String query = "SELECT *FROM bank_account where Account_no= ?";
          	Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/multiuserlogin", "root", "");
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, account1);
                rs = pst.executeQuery();
                if(rs.next()==false)
                {
                    JOptionPane.showMessageDialog(null, "User ID not found");
                }
                else 
                {
                   String Name = rs.getString("Name");
                  name.setText(Name.trim());
                    String Email = rs.getString("Email");
                  email.setText(Email.trim());
  String Number = rs.getString("Mobile_Number");
                  number.setText(Number.trim());
  String Money = rs.getString("Refund_Money");
                  date.setText(Money.trim());

                  
                      
                    
                }
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Manager_Order_Form.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Manager_Order_Form.class.getName()).log(Level.SEVERE, null, ex);
            }
            
           
           }
    }//GEN-LAST:event_accountKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        front_page p = new front_page();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manager_Your_bank_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manager_Your_bank_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manager_Your_bank_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manager_Your_bank_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manager_Your_bank_account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account;
    private javax.swing.JButton btnBestSellersCustomer;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMakeOrderCustomer;
    private javax.swing.JButton btnMenuCustomer;
    private javax.swing.JButton btnOrdersCustomer;
    private javax.swing.JTextField date;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField number;
    // End of variables declaration//GEN-END:variables
}
