/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Manager;

import Customer.*;
import User.Home;
import User.Sign_Up;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Manager_bank_account extends javax.swing.JFrame {

    /**
     * Creates new form bank_account
     */
    Connection con = null;
	PreparedStatement pst = null;
    public Manager_bank_account() {
        initComponents();
        showpic1();
    }
    public void showpic1()
    {
        ImageIcon icon = new ImageIcon("E:\\Enginnering Folder\\java\\Restaurent Managment Project\\src\\Picture\\wallpaper2you_512446.jpg");
        jLabel10.setIcon(icon);
        //scaling image for fit
        Image img = icon.getImage();
        Image imageScale = img.getScaledInstance(jLabel10.getWidth(), jLabel10.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imageScale);
        jLabel10.setIcon(scaledIcon);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnOrdersCustomer = new javax.swing.JButton();
        btnMakeOrderCustomer = new javax.swing.JButton();
        btnBestSellersCustomer = new javax.swing.JButton();
        btnMenuCustomer = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        account = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        time = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 120, 1096, 624));
        setMinimumSize(new java.awt.Dimension(1096, 624));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(null);

        btnLogout.setBackground(new java.awt.Color(13, 14, 14));
        btnLogout.setForeground(new java.awt.Color(0, 16, 14));
        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout);
        btnLogout.setBounds(980, 20, 100, 60);

        btnOrdersCustomer.setBackground(new java.awt.Color(13, 14, 14));
        btnOrdersCustomer.setForeground(new java.awt.Color(0, 16, 14));
        btnOrdersCustomer.setText("Your Orders");
        btnOrdersCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrdersCustomer);
        btnOrdersCustomer.setBounds(790, 20, 170, 60);

        btnMakeOrderCustomer.setBackground(new java.awt.Color(13, 14, 14));
        btnMakeOrderCustomer.setForeground(new java.awt.Color(0, 16, 14));
        btnMakeOrderCustomer.setText("Order");
        btnMakeOrderCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeOrderCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(btnMakeOrderCustomer);
        btnMakeOrderCustomer.setBounds(650, 20, 120, 60);

        btnBestSellersCustomer.setBackground(new java.awt.Color(13, 14, 14));
        btnBestSellersCustomer.setForeground(new java.awt.Color(0, 16, 14));
        btnBestSellersCustomer.setText("Best Selling Food");
        btnBestSellersCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBestSellersCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(btnBestSellersCustomer);
        btnBestSellersCustomer.setBounds(430, 20, 194, 60);

        btnMenuCustomer.setBackground(new java.awt.Color(13, 14, 14));
        btnMenuCustomer.setForeground(new java.awt.Color(0, 16, 14));
        btnMenuCustomer.setText("Menu");
        btnMenuCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenuCustomer);
        btnMenuCustomer.setBounds(320, 20, 100, 58);

        jLabel9.setFont(new java.awt.Font("Edwardian Script ITC", 1, 26)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 51));
        jLabel9.setText("KHS Cafe & Restaurent");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 10, 290, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 0);

        jPanel2.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Account No. : ");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(340, 200, 140, 30);
        jPanel2.add(account);
        account.setBounds(510, 200, 240, 30);

        jLabel1.setFont(new java.awt.Font("Edwardian Script ITC", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Your Bank Account");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(263, 18, 560, 100);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(340, 240, 121, 30);
        jPanel2.add(name);
        name.setBounds(510, 240, 244, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("E-Mail :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(340, 280, 121, 40);
        jPanel2.add(email);
        email.setBounds(510, 280, 244, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(340, 330, 121, 29);
        jPanel2.add(password);
        password.setBounds(510, 320, 244, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mobile number :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(340, 360, 140, 30);
        jPanel2.add(number);
        number.setBounds(510, 360, 244, 30);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Time :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(340, 400, 121, 27);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date (DD-MM-YY) :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(340, 440, 150, 26);
        jPanel2.add(date);
        date.setBounds(510, 440, 244, 30);

        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });
        jPanel2.add(time);
        time.setBounds(510, 400, 244, 30);

        add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(0, 0, 0));
        add.setText("Confirm");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add);
        add.setBounds(580, 490, 92, 35);

        jButton1.setText("<<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 582, 60, 30);

        jLabel10.setText("jLabel10");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(0, 0, 1100, 630);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1100, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnOrdersCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersCustomerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnOrdersCustomerActionPerformed

    private void btnMakeOrderCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeOrderCustomerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnMakeOrderCustomerActionPerformed

    private void btnBestSellersCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBestSellersCustomerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnBestSellersCustomerActionPerformed

    private void btnMenuCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuCustomerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnMenuCustomerActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        if(name.getText().equals("")||account.getText().equals("")||date.getText().equals("")||time.getText().equals("")||email.getText().equals("")||password.getText().equals("")||number.getText().equals("")||time.getText().equals(""))
         {
             JOptionPane.showMessageDialog(null, "Enter All information");
            
         }
         
                                               else
                                                {
                                        
					try
					{
						Class.forName("com.mysql.jdbc.Driver");
						String query = "INSERT INTO `bank_account`(`Name`,`Account_no`,`Email`,`Password`,`Mobile_Number`,`Time`,`Date`) VALUES (?,?,?,?,?,?,?)";
						con = DriverManager.getConnection("jdbc:mysql://localhost:3306/multiuserlogin", "root", "");
						pst = con.prepareStatement(query);
						pst.setString(1, name.getText());
                                                pst.setString(2, account.getText());
						pst.setString(3, email.getText());
						pst.setString(4, password.getText().toString());
						pst.setInt(5, Integer.valueOf(number.getText()));
						pst.setString(6, time.getText());
						pst.setString(7, date.getText());
                                                
						
						if(pst.executeUpdate()>0)
						{
							JOptionPane.showMessageDialog(null,"Bank Account created successfully");
						}
						
					} catch (Exception ex) {
                                     JOptionPane.showMessageDialog(null,"Please input another Email or Mobile Number");
                                        }
                                         name.setText("");
                                        password.setText("");
                                        account.setText("");
                                        email.setText("");
                                        number.setText("");
                                        date.setText("");
                                        time.setText("");
                                    }
				
    }//GEN-LAST:event_addActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        front_page p = new front_page();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager_bank_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager_bank_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager_bank_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager_bank_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager_bank_account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account;
    private javax.swing.JButton add;
    private javax.swing.JButton btnBestSellersCustomer;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMakeOrderCustomer;
    private javax.swing.JButton btnMenuCustomer;
    private javax.swing.JButton btnOrdersCustomer;
    private javax.swing.JTextField date;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField number;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables
}
